apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zauni-app-be.fullname" . }}
  labels:
    {{- include "zauni-app-be.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zauni-app-be.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zauni-app-be.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: hijackersvk/onpk-appbackend:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        env:
          {{- include "zauni-app-be.env" . | nindent 8 }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}