apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with buildah and
    pushes it to a registry
  params:
    - name: repo-url
      type: string
    - name: image-reference
      type: string
    - name: dockerfile
      type: string
    - name: context
      type: string
    - name: app-part
      type: string
  workspaces:
    - name: shared-data
    - name: docker-credentials
    - name: git-credentials
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: 1.0.0/main
      workspaces:
        - name: output
          workspace: shared-data
        - name: ssh-directory
          workspace: git-credentials
    - name: extract-tag
      runAfter: ["fetch-source"]
      params:
        - name: CONTEXT
          value: $(params.context)
      taskSpec:
        steps:
          - name: extract-tag
            image: alpine:3.18
            command: ["sh"]
            args:
              - "-c"
              - |
                #!/usr/bin/env sh
                ls -lha $(workspaces.source.path)/$(CONTEXT)/.git/
                cat $(workspaces.source.path)/$(CONTEXT)/.git/HEAD
                tag=$(cat $(workspaces.source.path)/$(CONTEXT)/.git/HEAD | cut -d'/' -f3)                
                echo $tag > $(workspaces.source.path)/tag.txt
                echo "Extracted tag: $tag"
      workspaces:
        - name: source
          workspace: shared-data
    - name: build-push
      runAfter: ["extract-tag"]
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.image-reference):$(cat $(workspaces.source.path)/tag.txt)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.context)
        - name: SKIP_PUSH
          value: false
        - name: FORMAT
          value: docker
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: docker-credentials
    - name: update-image-version
      runAfter: ["build-push"]
      params:
        - name: IMAGE
          value: $(params.image-reference):$(cat $(workspaces.source.path)/tag.txt)
        - name: APP-PART
          value: $(params.app-part)
      taskSpec:
        steps:
          - name: update-version
            image: alpine:3.18
            script: |
              #!/usr/bin/env sh
              apk add --no-cache yq
              yq -i '.image.tag = "$(IMAGE)"' $(workspaces.source.path)/helm/$(APP-PART)/values.yaml
          - name: check
            image: alpine:3.18
            command: ["cat"]
            args:
              - "$(workspaces.source.path)/helm/$(APP-PART)/values.yaml"
      workspaces:
        - name: source
          workspace: shared-data
    - name: deploy-app-partly
      runAfter: ["update-image-version"]
      params:
        - name: APP-PART
          value: $(params.app-part)
      taskSpec:
        steps:
          - name: deploy-helm-chart
            image: alpine:3.18
            command: ["helm"]
            args:
              - |
                upgrade $(APP-PART) $(workspaces.source.path)/helm/$(APP-PART)/ --values=$(workspaces.source.path)/helm/$(APP-PART)/values.yaml --install --create-namespace
      workspaces:
        - name: source
          workspace: shared-data