apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zauni-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    ingress.kubernetes.io/service-node-port: "31400"
spec:
  defaultBackend:
    service:
      name: {{ include "zauni-app-fe.fullname" . }}
      port:
        number: {{ .Values.service.port }}
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service: 
            name: {{ .Values.backend.name }}
            port:
              number: {{ .Values.backend.port }}
