apiVersion: v1
kind: Service
metadata:
  name: {{ include "zauni-app-fe.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "zauni-app-fe.name" . }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}