# Default values for zauni_app-fe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "stage"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  node-port: 31400

service:
  port: 8080
  type: ClusterIP
  targetPort: 8080

backend:
  port: 9080
  name: zauni-app-be