name: Build and Push Docker Image CI

on:
  push:
    branches: [ "main", "Citronik-ci" ]
  pull_request:
    branches: [ "main", "Citronik-ci" ]
    
env:
  tag: "${{ github.ref == 'refs/heads/main' && 'latest' || 'stage' }}"



jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set environment variables
        if: github.repository == 'octo-org/octo-repo-prod' 
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: zauni-zadanie-appfrontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ONPK-appfrontend:${{ env.tag }}

  build-backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: zauni-zadanie-appbackend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ONPK-appbackend:${{ env.tag }}
