name: Build and Push Docker Image CI

on:
  push:
    branches: [ "main", "1.0.0/git/ci" ]
  pull_request:
    branches: [ "main", "1.0.0/git/ci" ]
    
env:
  tag: "${{ github.ref == 'refs/heads/main' && 'latest' || 'stage' }}"

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set build directory
        run: |
          cd zauni-zadanie-appfrontend
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: zauni-zadanie-appfrontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/onpk-appfrontend:${{ env.tag }}

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set build directory
        run: |
          cd zauni-zadanie-appbackend
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: zauni-zadanie-appbackend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/onpk-appbackend:${{ env.tag }}